version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Clean & Assemble
          command: ./gradlew clean assemble
      - run:
          name: Unit Test
          command: ./gradlew test
      - store_test_results:
          path: backend/build/test-results/test
      - store_artifacts:
          path: backend/build/libs
