version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Clean & Assemble
          command: ./gradlew clean assemble
      - run:
          name: Unit Test
          command: ./gradlew test
